### ISSUE TITLE
Celery to be run automatically

### ISSUE THREAD

**Issue by morlandi** [Axelrod-Python/DjAxelrod#13]
Actually, as explained in the Readme, you have to run Celery manually

```
$ cd /vagrant
$ celery -A djalexrod worker -l info
```

Need to arrange an automotic startup procedure, similar to the one already used with the Django server.
Or better, have supervisor keep both services up and running

**Comment by mmcardle** [comment]
The docs have some good info in this
http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html?highlight=celeryd
