### ISSUE TITLE
Use Nginx, and run django service as non-root user

### ISSUE THREAD

**Issue by morlandi** [Axelrod-Python/DjAxelrod#14]
...

**Comment by meatballs** [comment]
Could you explain how this would be an improvement?

**Comment by morlandi** [comment]
While we download the full provisioning and build a VM for local testing, runserver is OK; however, with a little effort we could move toward a solution more suitable for deployment on a production server. Nginx would handle concurrent requests, and serve all static files (for example all bitmaps produced by each tournament) very efficiently with no need to involve Django; gunicorn would also be required to run Django as a WSGI application . It'a a fairly common Django setup for a production server

**Comment by meatballs** [comment]
I can see that would all be necessary for production. If we host at heroku, for example, that's precisely what we'd get. I can't see what we would gain by changing anything now, however. runserver is perfectly fine for our dev vm and our code would be fine at heroku.

**Comment by morlandi** [comment]
I understand your point of view; let's close this issue now and we might rediscuss it later on, when ready for the deployment of a working instance, which in my opinion would be necessary to share tornaments' results among people

**Comment by meatballs** [comment]
OK - A public instance is definitely required!! I'd like to get this up on heroku as quickly as we can. i just don't think we're quite ready yet.
