### ISSUE TITLE
Django debug toolbar not installing during provisioning

### ISSUE THREAD

**Issue by nealedj** [Axelrod-Python/DjAxelrod#17]
```
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named debug_toolbar
```

**Comment by meatballs** [comment]
That was fixed yesterday, I believe. You may just need to re-provision your vm
Commit: 618df4627bd72cc76f644454832ca642e2cb0a06

**Comment by meatballs** [comment]
I take that back! It's not working on a clean vm either.

**Comment by mmcardle** [comment]
there is a dev.txt with the debug toolbar requirement in it
change the deploy to 

```
pip install -r /vagrant/dev.txt
```

**Comment by meatballs** [comment]
Something in requirements.txt is breaking pip completely

**Comment by meatballs** [comment]
Looks like it's something to do with requests: https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991

**Comment by meatballs** [comment]
http://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

**Comment by meatballs** [comment]
Fixed by using eay_install to install pip rather than apt-get. Looks like the ubuntu package for pip is out of date
