### ISSUE TITLE
Change UI to allow multiple duplicate strategies to be selected for a tournament

### ISSUE THREAD

**Issue by nealedj** [Axelrod-Python/DjAxelrod#18]
At the moment only one of each strategy may be selected for a new tournament.

**Comment by langner** [comment]
Off-topic: is there a test version online somewhere?

**Comment by meatballs** [comment]
@nealedj Yes - absolutely agree with the need to do this
@langner No - this isn't hosted anywhere yet. You need to run a local instance in order to see where we're up to. (It's not anywhere near ready to be made public yet)

**Comment by drvinceknight** [comment]
:+1: :)

**Comment by drvinceknight** [comment]
Just played around with this, looks awesome :+1:

Only minor thing is the number box doesn't seem to quite fit? 

![screenshot 2015-06-22 08 45 25](https://cloud.githubusercontent.com/assets/2131546/8277476/1c3b5dcc-18bb-11e5-84c2-a638b235c890.png)

@meatballs this ok to go in?

**Comment by meatballs** [comment]
This is now breaking the graphical output which can't cope with more than one player of the same strategy. I think that should become a part of #44 rather than stopping this from progressing.

**Comment by meatballs** [comment]
The number box is displaying fine on Chrome and Safari as a simple text box, but on Firefox, it has the issue that @drvinceknight pointed out above

**Comment by drvinceknight** [comment]
When creating the multiple players they could/should just have a label 'Cooperator_0', 'Cooperator_1' etc.. Is that for #44 or would that be a simple enough fix?

**Comment by meatballs** [comment]
OK - I can do that now quite easily

**Comment by meatballs** [comment]
I'll have a crack at that now
done

**Comment by martinjc** [comment]
Just a quick note - adding numbers to the player names makes life harder on the front-end - I need to then remove the number to check against list of cheaters. Is it necessary to differentiate between multiple players? It's easy enough to change the vis code in #44 to deal with multiple instances of the same name (as in, it's already done ;-))

**Comment by meatballs** [comment]
@martinjc no, adding the numbers is not necessary. It was only done to ensure that the graph worked for this PR. If you can fix it in the graph itself, then it can go.

How about I create a branch for #44 , you submit a PR to that branch for the work you've done so far and then I make the changes to get rid of the numbering?

**Comment by martinjc** [comment]
sounds great!
