### ISSUE TITLE
Install matplotlib on Mac - SOLVED

### ISSUE THREAD

**Issue by morlandi** [Axelrod-Python/DjAxelrod#24]
Basically, you have to rename some XQuartz include file during installation.
Here's what I did on my macbook, based on what suggested at http://blog.matt-swain.com/post/87112978897/fixing-matplotlib-png-output-on-mac-os-x

```
pip uninstall matplotlib
cd /usr/X11/include
sudo mv png.h _png.h
sudo mv pngconf.h _pngconf.h
sudo mv pnglibconf.h _pnglibconf.h
pip install matplotlib
sudo mv _png.h png.h
sudo mv _pngconf.h pngconf.h
sudo mv _pnglibconf.h pnglibconf.h
```

**Comment by drvinceknight** [comment]
I'm not sure I understand, I've been able to use matplotlib on Mac, installing directly with `pip install matplotlib`.

**Comment by morlandi** [comment]
I was not so lucky ;) so this might depend on what's' installed on your machine.
Could be useful for someone else
