### ISSUE TITLE
Add turns, repetitions and noise

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/DjAxelrod#27]
to Tournament

**Comment by meatballs** [comment]
Work done so far is on branch 27, but I've hit a snag and would appreciate some help.

I've added turns, repetitions and noise to the tournament model, form and template. I've also created the migration. All good so far and the correct values are being stored in the db for the tournament definition.

However, the results are still coming back with 10 repetitions. I've even tried hard coding a value into the line that creates the axelrod.Tournament instance, and I still get results for 10 repetitions. What am I missing?

**Comment by mmcardle** [comment]
did you restart celery?

**Comment by meatballs** [comment]
It's the simple stuff that gets you every time! I'll try that later

**Comment by meatballs** [comment]
Yep - that did the trick.
And highlighted the fact that 'noise' doesn't exist in version 0.0.8 of the Axelrod library!
