### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/DjAxelrod#4]
Two main options with further sub-options:
1. Conventional Relational DB
   1. Postgresql
   2. MySql
   3. Something else
2. Non-Relational Database
   1. Document Database
      1. MongoDb
   2. Graph Database
      1. Neo4J
   3. OrientDB
   4. Something Else

**Comment by meatballs** [comment]
I can't see any reason to be particularly innovative here. I'd go with Postgresql.

**Comment by drvinceknight** [comment]
I'm once again happy to follow your lead.

**Comment by langner** [comment]
What do you need a database for?

**Comment by drvinceknight** [comment]
We're kind of talking about that on #5...

**Comment by meatballs** [comment]
Django requires a DB for its (mandatory) session and user management, if nothing else.

**Comment by meatballs** [comment]
the dj-database-url package makes this redundant as the db can be defined locally to be anything that's supported by Django.
