### ISSUE TITLE
Fixing graphical output

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/DjAxelrod#44]
As described on #40 there are some issues with the plotting output:
- The axes/scale is incorrect
- In `vis.js` the number of turns is hard coded (which is probably why the above fails)

I think the size of the plot could be reduced, I know it's apparently difficult to make d3 responsive but it would be nice to reduce the size slightly... (it barely fits on my 11inc air's screen).

**Comment by martinjc** [comment]
okay, happy to take a look at this one :-)

**Comment by drvinceknight** [comment]
Absolutely brilliant :+1: :D :fireworks:

**Comment by meatballs** [comment]
:+1: Fantastic! I get to avoid javascript a little longer!!

**Comment by meatballs** [comment]
Once #18 gets merged there will also be a problem for any tournament with more than one player of any given strategy not being displayed.

**Comment by meatballs** [comment]
branch 44 created for this issue

**Comment by meatballs** [comment]
I've removed the code that added numbers on to the player labels.
