### ISSUE TITLE
Gulp server hogging the CPU

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/DjAxelrod#48]
Is there something that can be done about the gulp server?

Would this be an issue when we host the app?

**Comment by meatballs** [comment]
If I knew what the problem was, I'd have fixed it already!

It's not an issue for a live app as there's no need for gulp at all then - Gulp is just a task runner and we're using it to monitor the static_dev folder for changes to files which it then reflects in the static folder.

**Comment by drvinceknight** [comment]
> If I knew what the problem was, I'd have fixed it already!

I thought as much :+1: 

Cool re live app :) What was the command again to kill it locally? I'll throw it on the readme (this is the ultimate procrastination, I really should be working on that paper).

**Comment by meatballs** [comment]
`vagrant ssh -c 'sudo stop gulp-server'`

**Comment by meatballs** [comment]
I've hit exactly the same problem when running gulp manually - it starts to hog the cpu.

this appears to be a known issue with gulp: https://github.com/gulpjs/gulp/issues/651
