### ISSUE TITLE
Hosting?

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/DjAxelrod#5]
Any reason to go with anything other than Heroku?

**Comment by drvinceknight** [comment]
None from my point of view.

**Comment by meatballs** [comment]
My slight concern here is that the DB will very quickly grow beyond the size where Heroku hosting is free (10 000 records, if memory serves).

**Comment by drvinceknight** [comment]
Why would the DB grow that much? Are you thinking that every run of every
tournament would be recorded?

**Comment by meatballs** [comment]
I can imagine that we might want to make various sets of results permanently available for analysis - possibly even allow users to specify if they wish to make their results public.

**Comment by drvinceknight** [comment]
Not against that but if it's going to be a constraint on our DB I don't
think it's necessary... Just being able to run a tournament and see the
results is cool, users could download all the output files as required...

**Comment by meatballs** [comment]
Yep - a longer term, 'nice to have' problem. Not worth worrying about yet!

**Comment by drvinceknight** [comment]
:+1:
