### ISSUE TITLE
Vagrant Virtual Machine

### ISSUE THREAD

**Issue by meatballs** [Axelrod-Python/DjAxelrod#6]
I think we should configure a vagrant VM for the project in order to:
- Simplify the configuration for developers - it will all be done on the vm and provisioned by vagrant
- Ensure that all developers are using the same environment

**Comment by drvinceknight** [comment]
:+1: Sounds good to me.

**Comment by meatballs** [comment]
Work so far is on branch 6 which pulls in my https://github.com/meatballs/vagrant-provisioning as a git submodule.

**Comment by meatballs** [comment]
The vagrant vm is now working. I'm hoping to get README.rst up to date today with the instructions to use it and then the branch should be ok to push and merge.

**Comment by drvinceknight** [comment]
Does this mean it's working?

https://www.dropbox.com/s/5pazd361f23sa7c/Screenshot%202015-04-23%2010.54.35.png?dl=0

**Comment by meatballs** [comment]
Certainly does!! Thats's the default screen of the  browseable API from Django Rest Framework

**Comment by drvinceknight** [comment]
Woops I meant to comment on #8...
